### ISSUE TITLE
about other datasets

### ISSUE THREAD

**Issue by DuTim** [hulkima/Tri-CDR#1]
Very nice work!

Would you consider uploading two other cross-domain recommendation task datasets to reproduce the results in the paper?

thanks

**Comment by hulkima** [comment]
Sorry for the late reply and thanks for your attention to our Tri-CDR. I apologise for cleaning up the big files after graduation when the server's SSD was full, except for certain essential code files. I have found them in the backup file and uploaded some of the pre-process files of our Tri-CDR in this Google Drive link: https://drive.google.com/drive/folders/1uhw-EjtADGkNQbiGKbMsIUGWxPTvV0XU?usp=drive_link. You can leverage these files to generate the corresponding datasets. I hope this helps!
