### ISSUE TITLE
Sequence alignment of prediction

### ISSUE THREAD

**Issue by DiMarzioBian** [hulkima/Tri-CDR#2]
Dear authors,

I found alignment mismatch between mix/src/tgt sequences features in line 272 of model.py.

From your code, all mix/src/tgt sequences are padded in the front to have the same length but no padding inside the sequences. As a consequence, there will be some training tgt interactions either seeing future training interactions or not seeing the complete past interactions in mix and source domains. Only the last interactions of these training sequences are correctly concated.

**Comment by hulkima** [comment]
Sorry for the late reply and thanks for your attention to our Tri-CDR. For this question, we actually ALIGN the behaviour of mixed sequences and source sequences corresponding to target sequences in get_mask_matrix() at line 418 of model.py with the parameter sequence_for_target_indices, which is generated in the data_loader and sampler in utils.py. With this parameter, we could mask out future behaviours and exactly locate the mixed and source behaviors of each corresponding interaction in the target domain. I hope this would be helpful, thanks!
