### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by Alpacanm** [hulkima/Tri-CDR#3]
Dear Author,

Your research results are impressive; however, the dataset provided with the code includes only Amazon's Game and Toy datasets, and the relevant code is limited to these datasets. There is no processing or support for the other two datasets mentioned in the paper. I hope you can provide the complete datasets to enable replication of the experimental results. If you could offer this support, I would greatly appreciate it.

**Comment by hulkima** [comment]
Sorry for the late reply and thanks for your attention to our Tri-CDR. I apologise for cleaning up the big files after graduation when the server's SSD was full, except for certain essential code files. I have found them in the backup file and uploaded some of the pre-process files of our Tri-CDR in this Google Drive link: https://drive.google.com/drive/folders/1uhw-EjtADGkNQbiGKbMsIUGWxPTvV0XU?usp=drive_link. You can leverage these files to generate the corresponding datasets. I hope this helps!
